### ISSUE TITLE
Spaces between words <w> 

### ISSUE THREAD

**Issue by catsmith** [scribe777/wfce-ote#34]
Troy to send logic

**Comment by scribe777** [comment]
`	static public String fixTranscription(String text, Page p) {
		if (text.indexOf("<TEI ") > -1) {
			text = text.substring(text.indexOf("<TEI "));
		}
//logger.info("text before fix: " + text);
// to handle: </w><ex rend="ȣ">ου</ex>
		text = text.replaceAll("</w> *(<ex[^>]*>[^<]*</ex>)",  "</w> <w>$1</w>");
		text = text.replaceAll("(<ex[^>]*>[^<]*</ex>) *(<w[> ])",  "<w>$1</w> $2");
		text = text.replace("<w/>",                          "");
		text = text.replace("<ab/>",                         "");
		text = text.replace("<supplied></supplied>",         "");
		text = text.replace("<w></w>",                       " ");
		text = text.replace("</w><w>",                       "</w> <w>");
		text = text.replace("</w><w ",                       "</w> <w ");
		text = text.replace("</pc><w>",                      "</pc> <w>");
		text = text.replace("</pc><w ",                      "</pc> <w ");
		text = text.replace("</pc><ex",                      "</pc> <ex");
		text = text.replace("</ex><w>",                     "</ex> <w>");
		text = text.replace("</seg><w>",                     "</seg> <w>");
		text = text.replace("</pc><app>",                    "</pc> <app>");
		text = text.replace("</note><w>",                    "</note> <w>");
		text = text.replace("</note></ab><ab",               "</note></ab> <ab");
		text = text.replace("</w></ab><ab",                  "</w></ab> <ab");
		text = text.replace("</note><app",                   "</note> <app");
		text = text.replace("</app><w>",                     "</app> <w>");
		text = text.replace("</w><app",                      "</w> <app");
		text = text.replace("</w><space",                    "</w> <space");
		text = text.replace("</w><gap ",                     "</w> <gap ");
		text = text.replace(" </ab><ab",                     "</ab> <ab");
		text = text.replace("</ab><ab",                      "</ab> <ab");
		text = text.replaceAll("<supplied[^>]*></supplied>", "");
		text = text.replaceAll("(<gap [^>]*/>)<w>",          "$1 <w>");
		text = text.replaceAll("</w></ab></div>([^ ])",      "</w></ab></div> $1");
		text = text.replaceAll("</pc></ab></div>([^ ])",      "</pc></ab></div> $1");

		// added to keep imports with no <w> from being joined together into one word in the OTE
		text = text.replace("</supplied> <supplied",         "</supplied><w></w><supplied");
		text = text.replace("</unclear> <unclear",           "</unclear><w></w><unclear");

		// only renumber breaks if we're processing a whole page
		if (p != null) {
			text = renumberBreaks(text, p);		
		}

		text = fixOTEDeficiencies(text);
		
//logger.info("text after fix: " + text);
		return text;
	}

`

**Comment by catsmith** [comment]
@scribe777 When you are feeling up to it please could you explain what this part is doing?

`// to handle: </w><ex rend="ȣ">ου</ex>
		text = text.replaceAll("</w> *(<ex[^>]*>[^<]*</ex>)",  "</w> <w>$1</w>");
		text = text.replaceAll("(<ex[^>]*>[^<]*</ex>) *(<w[> ])",  "<w>$1</w> $2");`

If that is just dealing with whole word ex tags we shouldn't need it anymore because you have already fixed that.

**Comment by catsmith** [comment]
Note to me: 

These lines don't deal with spaces so should be added somewhere regardless of the setting

```
text = text.replace("<w/>",                          "");
text = text.replace("<ab/>",                         "");
text = text.replace("<supplied></supplied>",         "");
text = text.replace("<w></w>",                       " ");
```

**Comment by catsmith** [comment]
@scribe777 Here are some more lines that I don't understand the reason for (despite the comment). They are definitely not adding spaces so they don't belong in the adding spaces code but do we still need them for the export?

```
// added to keep imports with no <w> from being joined together into one word in the OTE
text = text.replace("</supplied> <supplied",         "</supplied><w></w><supplied");
text = text.replace("</unclear> <unclear",           "</unclear><w></w><unclear");
```

**Comment by catsmith** [comment]
Lines from regex list not needed for the following reasons:

These two deal with whole word <ex> tags without the wrapping <w> which we have already fixed in the OTE now so no longer needed.

```
str = str.replace(/<\/pc><ex/g, '</pc> <ex');
str = str.replace(/<\/ex><w>/g, '</ex> <w>');
```

These two are already handled by the more generic </ab><ab> regex which was also in the original list and is still in the new one.

```
str = str.replace(/<\/note><\/ab><ab/g, '</note></ab> <ab');
str = str.replace(/<\/w><\/ab><ab/g, '</w></ab> <ab');
```
